"""generator runs

Revision ID: 01eef46f6a35
Revises: 2890bd5f860b
Create Date: 2026-10-02 10:44:11.501658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01eef46f6a35'
down_revision = '2890bd5f860b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generator_run',
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('result_timetable_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.Enum('full', 'repair', 'fill', name='gen_mode', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('status', sa.Enum('queued', 'feasibility_failed', 'running', 'solved', 'partial', 'infeasible', 'timeout', 'cancelled', 'failed', name='gen_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('feasibility', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('infeasible_core', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('objective', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_generator_run_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['result_timetable_id'], ['timetable.id'], name=op.f('fk_generator_run_result_timetable_id_timetable')),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], name=op.f('fk_generator_run_timetable_id_timetable')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_generator_run_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generator_run'))
    )
    with op.batch_alter_table('generator_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generator_run_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_generator_run_result_timetable_id'), ['result_timetable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generator_run_timetable_id'), ['timetable_id'], unique=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_student_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_student_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_student_updated_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_student_created_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('generator_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generator_run_timetable_id'))
        batch_op.drop_index(batch_op.f('ix_generator_run_result_timetable_id'))
        batch_op.drop_index(batch_op.f('ix_generator_run_change_seq'))

    op.drop_table('generator_run')
    # ### end Alembic commands ###
