"""students and email log

Revision ID: 2890bd5f860b
Revises: c42459b5a692
Create Date: 2026-10-02 09:15:38.194333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2890bd5f860b'
down_revision = 'c42459b5a692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('to_address', sa.Text(), nullable=False),
    sa.Column('to_name', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', name='mail_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['sent_by'], ['app_user.id'], name=op.f('fk_email_log_sent_by_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_log'))
    )
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_email_log_kind', ['kind'], unique=False)

    op.create_table('student',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('student_no', sa.String(length=40), nullable=True),
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('gender', sa.Enum('m', 'f', name='gender', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('group_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('guardian_phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_student_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], name=op.f('fk_student_section_id_section')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_student_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student'))
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_section_id'), ['section_id'], unique=False)
        batch_op.create_index('uq_student_no_live', ['student_no'], unique=True, postgresql_where=sa.text('student_no IS NOT NULL AND deleted_at IS NULL'), postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('substitution', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_substitution_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_substitution_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)

    with op.batch_alter_table('teacher_absence', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_teacher_absence_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_teacher_absence_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_absence', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_teacher_absence_updated_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_teacher_absence_created_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('substitution', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_substitution_created_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_substitution_updated_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index('uq_student_no_live', postgresql_where=sa.text('student_no IS NOT NULL AND deleted_at IS NULL'), postgresql_nulls_not_distinct=False)
        batch_op.drop_index(batch_op.f('ix_student_section_id'))
        batch_op.drop_index(batch_op.f('ix_student_change_seq'))

    op.drop_table('student')
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.drop_index('ix_email_log_kind')
        batch_op.drop_index(batch_op.f('ix_email_log_created_at'))

    op.drop_table('email_log')
    # ### end Alembic commands ###
