"""meetings: lesson kind, title, load flag, timing; teacher head of department

Revision ID: 31265e3d2864
Revises: 01eef46f6a35
Create Date: 2026-10-02 19:06:52.134723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31265e3d2864'
down_revision = '01eef46f6a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.Enum('lesson', 'meeting', name='lesson_kind', native_enum=False, create_constraint=True, length=20), server_default='lesson', nullable=False))
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('counts_load', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('bell_schedule_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lesson_bell_schedule_id'), ['bell_schedule_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_lesson_bell_schedule_id_bell_schedule'), 'bell_schedule', ['bell_schedule_id'], ['id'])

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_head', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('is_head')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lesson_bell_schedule_id_bell_schedule'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lesson_bell_schedule_id'))
        batch_op.drop_column('bell_schedule_id')
        batch_op.drop_column('counts_load')
        batch_op.drop_column('title')
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
