"""school logo upload

Revision ID: 5bfbb183f43e
Revises: 717f7cbd301e
Create Date: 2026-09-27 21:50:29.391087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bfbb183f43e'
down_revision = '717f7cbd301e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('logo_mime', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_column('logo_mime')
        batch_op.drop_column('logo_data')

    # ### end Alembic commands ###
