"""holidays and period plans

Revision ID: 6460d0aed9ca
Revises: c1b98fac5779
Create Date: 2026-10-02 20:09:10.582290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6460d0aed9ca'
down_revision = 'c1b98fac5779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holiday',
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('kind', sa.Enum('official', 'term_break', 'exams', 'activity', 'other', name='holiday_kind', native_enum=False, create_constraint=True, length=20), server_default='official', nullable=False),
    sa.Column('stage_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('stops_lessons', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('date_to >= date_from', name=op.f('ck_holiday_holiday_dates')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_holiday_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_holiday_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holiday'))
    )
    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holiday_change_seq'), ['change_seq'], unique=False)

    op.create_table('period_plan',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('period_type', sa.Enum('term', 'month', 'week', 'day', name='plan_period_type', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', name='plan_status', native_enum=False, create_constraint=True, length=20), server_default='draft', nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('targets', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['app_user.id'], name=op.f('fk_period_plan_approved_by_app_user')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_period_plan_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], name=op.f('fk_period_plan_stage_id_stage')),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], name=op.f('fk_period_plan_term_id_term')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_period_plan_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_period_plan'))
    )
    with op.batch_alter_table('period_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_period_plan_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_period_plan_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_period_plan_term_id'), ['term_id'], unique=False)

    with op.batch_alter_table('curriculum_item', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_curriculum_item_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_curriculum_item_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curriculum_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_curriculum_item_updated_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_curriculum_item_created_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('period_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_period_plan_term_id'))
        batch_op.drop_index(batch_op.f('ix_period_plan_stage_id'))
        batch_op.drop_index(batch_op.f('ix_period_plan_change_seq'))

    op.drop_table('period_plan')
    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holiday_change_seq'))

    op.drop_table('holiday')
    # ### end Alembic commands ###
