"""initial schema

Revision ID: 717f7cbd301e
Revises: 
Create Date: 2026-09-27 19:58:53.601712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '717f7cbd301e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Extensions: btree_gist for the occupancy EXCLUDE constraint, citext for case-insensitive emails.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # One global sequence feeds change_seq on every synced table (delta sync, ERD §1).
    op.execute("CREATE SEQUENCE IF NOT EXISTS global_change_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_year',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_academic_year_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_academic_year_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_year'))
    )
    with op.batch_alter_table('academic_year', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_year_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index('uq_academic_year_name_live', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)
        batch_op.create_index('uq_academic_year_one_current', ['is_current'], unique=True, postgresql_where=sa.text('is_current AND deleted_at IS NULL'), postgresql_nulls_not_distinct=False)

    op.create_table('app_setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_setting'))
    )
    op.create_table('app_user',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('ms_oid', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Enum('admin', 'stage_editor', 'viewer', name='user_role', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('preferred_lang', sa.Enum('ar', 'en', name='user_lang', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_app_user_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_app_user_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user'))
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_user_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index('uq_app_user_email_live', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)
        batch_op.create_index('uq_app_user_ms_oid_live', ['ms_oid'], unique=True, postgresql_where=sa.text('ms_oid IS NOT NULL AND deleted_at IS NULL'), postgresql_nulls_not_distinct=False)

    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)

    op.create_table('building',
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_building_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_building_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_building'))
    )
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_building_change_seq'), ['change_seq'], unique=False)

    op.create_table('school',
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.Column('default_lang', sa.Enum('ar', 'en', name='lang', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_school_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_school_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school'))
    )
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_change_seq'), ['change_seq'], unique=False)

    op.create_table('stage',
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_stage_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_stage_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage'))
    )
    with op.batch_alter_table('stage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_change_seq'), ['change_seq'], unique=False)

    op.create_table('subject',
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('short_ar', sa.String(length=20), nullable=True),
    sa.Column('short_en', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('max_teachers_per_block', sa.Integer(), nullable=False),
    sa.Column('requires_room_type', sa.String(length=30), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('max_teachers_per_block >= 1', name=op.f('ck_subject_max_teachers_pos')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_subject_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_subject_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject'))
    )
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_change_seq'), ['change_seq'], unique=False)

    op.create_table('weekday',
    sa.Column('iso_dow', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_school_day', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('iso_dow BETWEEN 1 AND 7', name=op.f('ck_weekday_dow_range')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_weekday_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_weekday_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekday'))
    )
    with op.batch_alter_table('weekday', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekday_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index('uq_weekday_dow_live', ['iso_dow'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)

    op.create_table('bell_schedule',
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_bell_schedule_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], name=op.f('fk_bell_schedule_stage_id_stage')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_bell_schedule_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bell_schedule'))
    )
    with op.batch_alter_table('bell_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bell_schedule_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_bell_schedule_stage_id'), ['stage_id'], unique=False)

    op.create_table('grade',
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_grade_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], name=op.f('fk_grade_stage_id_stage')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_grade_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade'))
    )
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_grade_stage_id'), ['stage_id'], unique=False)

    op.create_table('idempotency_key',
    sa.Column('key', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_idempotency_key_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_idempotency_key'))
    )
    with op.batch_alter_table('idempotency_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_key_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_key_user_id'), ['user_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title_ar', sa.Text(), nullable=False),
    sa.Column('title_en', sa.Text(), nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('push_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_notification_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('push_subscription',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_push_subscription_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscription')),
    sa.UniqueConstraint('endpoint', name=op.f('uq_push_subscription_endpoint'))
    )
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscription_user_id'), ['user_id'], unique=False)

    op.create_table('room',
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('short', sa.String(length=20), nullable=True),
    sa.Column('room_type', sa.String(length=30), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], name=op.f('fk_room_building_id_building')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_room_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_room_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room'))
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_change_seq'), ['change_seq'], unique=False)

    op.create_table('teacher',
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('short', sa.String(length=20), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('gender', sa.Enum('m', 'f', name='gender', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('target_weekly_periods', sa.Integer(), nullable=True),
    sa.Column('max_periods_per_day', sa.Integer(), nullable=True),
    sa.Column('max_gaps_per_day', sa.Integer(), nullable=True),
    sa.Column('max_gaps_per_week', sa.Integer(), nullable=True),
    sa.Column('max_consecutive', sa.Integer(), nullable=True),
    sa.Column('max_days_per_week', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_teacher_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_teacher_updated_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_teacher_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher'))
    )
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_teacher_user_live', ['user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL AND deleted_at IS NULL'), postgresql_nulls_not_distinct=False)

    op.create_table('term',
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_year.id'], name=op.f('fk_term_academic_year_id_academic_year')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_term_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_term_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_term'))
    )
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_term_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_term_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index('uq_term_year_ordinal_live', ['academic_year_id', 'ordinal'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)

    op.create_table('user_stage',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], name=op.f('fk_user_stage_stage_id_stage'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_user_stage_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'stage_id', name=op.f('pk_user_stage'))
    )
    op.create_table('bell_assignment',
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('weekday_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('bell_schedule_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['bell_schedule_id'], ['bell_schedule.id'], name=op.f('fk_bell_assignment_bell_schedule_id_bell_schedule')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_bell_assignment_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], name=op.f('fk_bell_assignment_grade_id_grade')),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], name=op.f('fk_bell_assignment_stage_id_stage')),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], name=op.f('fk_bell_assignment_term_id_term')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_bell_assignment_updated_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['weekday_id'], ['weekday.id'], name=op.f('fk_bell_assignment_weekday_id_weekday')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bell_assignment'))
    )
    with op.batch_alter_table('bell_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bell_assignment_bell_schedule_id'), ['bell_schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bell_assignment_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_bell_assignment_grade_id'), ['grade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bell_assignment_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bell_assignment_term_id'), ['term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bell_assignment_weekday_id'), ['weekday_id'], unique=False)
        batch_op.create_index('uq_bell_assignment_live', ['term_id', 'weekday_id', 'stage_id', 'grade_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=True)

    op.create_table('bell_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bell_schedule_id', sa.UUID(), nullable=False),
    sa.Column('slot_no', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('lesson', 'break', name='slot_kind', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('period_no', sa.Integer(), nullable=True),
    sa.Column('label_ar', sa.Text(), nullable=True),
    sa.Column('label_en', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.CheckConstraint("(kind = 'lesson') = (period_no IS NOT NULL)", name=op.f('ck_bell_slot_lesson_has_period')),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_bell_slot_slot_time_order')),
    sa.ForeignKeyConstraint(['bell_schedule_id'], ['bell_schedule.id'], name=op.f('fk_bell_slot_bell_schedule_id_bell_schedule'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bell_slot'))
    )
    with op.batch_alter_table('bell_slot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bell_slot_bell_schedule_id'), ['bell_schedule_id'], unique=False)
        batch_op.create_index('uq_bell_slot_no', ['bell_schedule_id', 'slot_no'], unique=True)
        batch_op.create_index('uq_bell_slot_period', ['bell_schedule_id', 'period_no'], unique=True, postgresql_where=sa.text('period_no IS NOT NULL'))

    op.create_table('section',
    sa.Column('grade_id', sa.UUID(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('home_room_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_section_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], name=op.f('fk_section_grade_id_grade')),
    sa.ForeignKeyConstraint(['home_room_id'], ['room.id'], name=op.f('fk_section_home_room_id_room')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_section_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_section'))
    )
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_section_grade_id'), ['grade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_section_home_room_id'), ['home_room_id'], unique=False)
        batch_op.create_index('uq_section_grade_name_live', ['grade_id', 'name_ar'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)

    op.create_table('subject_room',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_subject_room_room_id_room'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_subject_room_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'room_id', name=op.f('pk_subject_room'))
    )
    op.create_table('teacher_stage',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], name=op.f('fk_teacher_stage_stage_id_stage'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_teacher_stage_teacher_id_teacher'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'stage_id', name=op.f('pk_teacher_stage'))
    )
    op.create_table('teacher_subject',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_teacher_subject_subject_id_subject'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_teacher_subject_teacher_id_teacher'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'subject_id', name=op.f('pk_teacher_subject'))
    )
    op.create_table('timetable',
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='tt_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('cycle_weeks', sa.Integer(), nullable=False),
    sa.Column('based_on_id', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('cycle_weeks BETWEEN 1 AND 4', name=op.f('ck_timetable_cycle_weeks_range')),
    sa.ForeignKeyConstraint(['based_on_id'], ['timetable.id'], name=op.f('fk_timetable_based_on_id_timetable')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_timetable_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['published_by'], ['app_user.id'], name=op.f('fk_timetable_published_by_app_user')),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], name=op.f('fk_timetable_term_id_term')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_timetable_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timetable'))
    )
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timetable_based_on_id'), ['based_on_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timetable_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_timetable_term_id'), ['term_id'], unique=False)
        batch_op.create_index('uq_timetable_one_published', ['term_id'], unique=True, postgresql_where=sa.text("status = 'published' AND deleted_at IS NULL"), postgresql_nulls_not_distinct=False)

    op.create_table('availability',
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('teacher', 'section', 'subject', 'room', name='avail_entity', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('weekday_id', sa.UUID(), nullable=False),
    sa.Column('period_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('unavailable', 'conditional', name='avail_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_availability_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], name=op.f('fk_availability_timetable_id_timetable')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_availability_updated_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['weekday_id'], ['weekday.id'], name=op.f('fk_availability_weekday_id_weekday')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability'))
    )
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_availability_timetable_id'), ['timetable_id'], unique=False)
        batch_op.create_index('uq_availability_live', ['timetable_id', 'entity_type', 'entity_id', 'weekday_id', 'period_no'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)

    op.create_table('constraint_rule',
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('scope_type', sa.Enum('subject', 'lesson', 'teacher', 'section', 'grade', 'stage', 'global', name='rule_scope', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('scope_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('strength', sa.Enum('hard', 'soft', name='rule_strength', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_constraint_rule_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], name=op.f('fk_constraint_rule_timetable_id_timetable')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_constraint_rule_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_constraint_rule'))
    )
    with op.batch_alter_table('constraint_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_constraint_rule_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_constraint_rule_timetable_id'), ['timetable_id'], unique=False)

    op.create_table('division',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_division_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], name=op.f('fk_division_section_id_section')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_division_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_division'))
    )
    with op.batch_alter_table('division', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_division_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_division_section_id'), ['section_id'], unique=False)

    op.create_table('lesson',
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('periods_per_week', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=True),
    sa.Column('preferred_room_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('duration BETWEEN 1 AND 4', name=op.f('ck_lesson_duration_range')),
    sa.CheckConstraint('periods_per_week >= 1', name=op.f('ck_lesson_ppw_pos')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_lesson_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['preferred_room_id'], ['room.id'], name=op.f('fk_lesson_preferred_room_id_room')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_lesson_subject_id_subject')),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], name=op.f('fk_lesson_timetable_id_timetable')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_lesson_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson'))
    )
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_preferred_room_id'), ['preferred_room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_timetable_id'), ['timetable_id'], unique=False)

    op.create_table('card',
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('weekday_id', sa.UUID(), nullable=True),
    sa.Column('period_no', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('(weekday_id IS NULL) = (period_no IS NULL)', name=op.f('ck_card_placed_consistent')),
    sa.CheckConstraint('duration BETWEEN 1 AND 4', name=op.f('ck_card_card_duration_range')),
    sa.CheckConstraint('period_no IS NULL OR period_no >= 1', name=op.f('ck_card_period_pos')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_card_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name=op.f('fk_card_lesson_id_lesson')),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_card_room_id_room')),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], name=op.f('fk_card_timetable_id_timetable')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_card_updated_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['weekday_id'], ['weekday.id'], name=op.f('fk_card_weekday_id_weekday')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card'))
    )
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_room_id'), ['room_id'], unique=False)
        batch_op.create_index('ix_card_slot', ['timetable_id', 'weekday_id', 'period_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_timetable_id'), ['timetable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_weekday_id'), ['weekday_id'], unique=False)

    op.create_table('lesson_teacher',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('main', 'assistant', name='teacher_role', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name=op.f('fk_lesson_teacher_lesson_id_lesson'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_lesson_teacher_teacher_id_teacher')),
    sa.PrimaryKeyConstraint('lesson_id', 'teacher_id', name=op.f('pk_lesson_teacher'))
    )
    with op.batch_alter_table('lesson_teacher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_teacher_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('student_group',
    sa.Column('division_id', sa.UUID(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_student_group_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], name=op.f('fk_student_group_division_id_division')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_student_group_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_group'))
    )
    with op.batch_alter_table('student_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_group_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_group_division_id'), ['division_id'], unique=False)

    op.create_table('lesson_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['student_group.id'], name=op.f('fk_lesson_target_group_id_student_group')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name=op.f('fk_lesson_target_lesson_id_lesson'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], name=op.f('fk_lesson_target_section_id_section')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_target'))
    )
    with op.batch_alter_table('lesson_target', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_target_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_target_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_target_section_id'), ['section_id'], unique=False)
        batch_op.create_index('uq_lesson_target', ['lesson_id', 'section_id', 'group_id'], unique=True, postgresql_nulls_not_distinct=True)

    op.create_table('occupancy',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Enum('teacher', 'room', name='occ_resource', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('weekday_id', sa.UUID(), nullable=False),
    sa.Column('periods', postgresql.INT4RANGE(), nullable=False),
    sa.Column('weeks', postgresql.INT4RANGE(), nullable=False),
    postgresql.ExcludeConstraint((sa.column('timetable_id'), '='), (sa.column('resource_type'), '='), (sa.column('resource_id'), '='), (sa.column('weekday_id'), '='), (sa.column('periods'), '&&'), (sa.column('weeks'), '&&'), using='gist', name='ex_occupancy_no_overlap'),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_occupancy_card_id_card'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], name=op.f('fk_occupancy_timetable_id_timetable')),
    sa.ForeignKeyConstraint(['weekday_id'], ['weekday.id'], name=op.f('fk_occupancy_weekday_id_weekday')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_occupancy'))
    )
    with op.batch_alter_table('occupancy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_occupancy_card_id'), ['card_id'], unique=False)

    # ### end Alembic commands ###

    # created_by / updated_by audit FKs to app_user (use_alter: added after all tables exist)
    with op.batch_alter_table('academic_year', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_academic_year_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_academic_year_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)

    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_app_user_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_app_user_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)

    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_availability_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_availability_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)

    with op.batch_alter_table('bell_assignment', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_bell_assignment_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_bell_assignment_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)

    with op.batch_alter_table('bell_schedule', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_bell_schedule_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_bell_schedule_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)

    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_building_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_building_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_card_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_card_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)

    with op.batch_alter_table('constraint_rule', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_constraint_rule_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_constraint_rule_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)

    with op.batch_alter_table('division', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_division_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_division_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_grade_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_grade_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_lesson_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_lesson_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_room_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_room_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_school_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_school_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_section_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_section_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)

    with op.batch_alter_table('stage', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_stage_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_stage_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)

    with op.batch_alter_table('student_group', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_student_group_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_student_group_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_subject_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_subject_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_teacher_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_teacher_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)

    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_term_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_term_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)

    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_timetable_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_timetable_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)

    with op.batch_alter_table('weekday', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_weekday_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_weekday_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)


def downgrade():
    with op.batch_alter_table('weekday', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_weekday_updated_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_weekday_created_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_timetable_created_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_timetable_updated_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_term_created_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_term_updated_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_teacher_created_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_teacher_updated_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_subject_updated_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_subject_created_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('student_group', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_student_group_created_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_student_group_updated_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('stage', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stage_created_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stage_updated_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_section_updated_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_section_created_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_school_updated_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_school_created_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_room_updated_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_room_created_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lesson_created_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_lesson_updated_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_grade_updated_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_grade_created_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('division', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_division_created_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_division_updated_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('constraint_rule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_constraint_rule_created_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_constraint_rule_updated_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_card_created_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_card_updated_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_building_updated_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_building_created_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('bell_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bell_schedule_updated_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_bell_schedule_created_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('bell_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bell_assignment_created_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_bell_assignment_updated_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_availability_updated_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_availability_created_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_app_user_updated_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_app_user_created_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('academic_year', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_academic_year_created_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_academic_year_updated_by_app_user'), type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupancy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occupancy_card_id'))

    op.drop_table('occupancy')
    with op.batch_alter_table('lesson_target', schema=None) as batch_op:
        batch_op.drop_index('uq_lesson_target', postgresql_nulls_not_distinct=True)
        batch_op.drop_index(batch_op.f('ix_lesson_target_section_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_target_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_target_group_id'))

    op.drop_table('lesson_target')
    with op.batch_alter_table('student_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_group_division_id'))
        batch_op.drop_index(batch_op.f('ix_student_group_change_seq'))

    op.drop_table('student_group')
    with op.batch_alter_table('lesson_teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_teacher_teacher_id'))

    op.drop_table('lesson_teacher')
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_weekday_id'))
        batch_op.drop_index(batch_op.f('ix_card_timetable_id'))
        batch_op.drop_index('ix_card_slot')
        batch_op.drop_index(batch_op.f('ix_card_room_id'))
        batch_op.drop_index(batch_op.f('ix_card_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_card_change_seq'))

    op.drop_table('card')
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_timetable_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_subject_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_preferred_room_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_change_seq'))

    op.drop_table('lesson')
    with op.batch_alter_table('division', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_division_section_id'))
        batch_op.drop_index(batch_op.f('ix_division_change_seq'))

    op.drop_table('division')
    with op.batch_alter_table('constraint_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_constraint_rule_timetable_id'))
        batch_op.drop_index(batch_op.f('ix_constraint_rule_change_seq'))

    op.drop_table('constraint_rule')
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_index('uq_availability_live', postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)
        batch_op.drop_index(batch_op.f('ix_availability_timetable_id'))
        batch_op.drop_index(batch_op.f('ix_availability_change_seq'))

    op.drop_table('availability')
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.drop_index('uq_timetable_one_published', postgresql_where=sa.text("status = 'published' AND deleted_at IS NULL"), postgresql_nulls_not_distinct=False)
        batch_op.drop_index(batch_op.f('ix_timetable_term_id'))
        batch_op.drop_index(batch_op.f('ix_timetable_change_seq'))
        batch_op.drop_index(batch_op.f('ix_timetable_based_on_id'))

    op.drop_table('timetable')
    op.drop_table('teacher_subject')
    op.drop_table('teacher_stage')
    op.drop_table('subject_room')
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_index('uq_section_grade_name_live', postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)
        batch_op.drop_index(batch_op.f('ix_section_home_room_id'))
        batch_op.drop_index(batch_op.f('ix_section_grade_id'))
        batch_op.drop_index(batch_op.f('ix_section_change_seq'))

    op.drop_table('section')
    with op.batch_alter_table('bell_slot', schema=None) as batch_op:
        batch_op.drop_index('uq_bell_slot_period', postgresql_where=sa.text('period_no IS NOT NULL'))
        batch_op.drop_index('uq_bell_slot_no')
        batch_op.drop_index(batch_op.f('ix_bell_slot_bell_schedule_id'))

    op.drop_table('bell_slot')
    with op.batch_alter_table('bell_assignment', schema=None) as batch_op:
        batch_op.drop_index('uq_bell_assignment_live', postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=True)
        batch_op.drop_index(batch_op.f('ix_bell_assignment_weekday_id'))
        batch_op.drop_index(batch_op.f('ix_bell_assignment_term_id'))
        batch_op.drop_index(batch_op.f('ix_bell_assignment_stage_id'))
        batch_op.drop_index(batch_op.f('ix_bell_assignment_grade_id'))
        batch_op.drop_index(batch_op.f('ix_bell_assignment_change_seq'))
        batch_op.drop_index(batch_op.f('ix_bell_assignment_bell_schedule_id'))

    op.drop_table('bell_assignment')
    op.drop_table('user_stage')
    with op.batch_alter_table('term', schema=None) as batch_op:
        batch_op.drop_index('uq_term_year_ordinal_live', postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)
        batch_op.drop_index(batch_op.f('ix_term_change_seq'))
        batch_op.drop_index(batch_op.f('ix_term_academic_year_id'))

    op.drop_table('term')
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_index('uq_teacher_user_live', postgresql_where=sa.text('user_id IS NOT NULL AND deleted_at IS NULL'), postgresql_nulls_not_distinct=False)
        batch_op.drop_index(batch_op.f('ix_teacher_user_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_change_seq'))

    op.drop_table('teacher')
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_change_seq'))
        batch_op.drop_index(batch_op.f('ix_room_building_id'))

    op.drop_table('room')
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscription_user_id'))

    op.drop_table('push_subscription')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    op.drop_table('notification')
    with op.batch_alter_table('idempotency_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_key_user_id'))
        batch_op.drop_index(batch_op.f('ix_idempotency_key_expires_at'))

    op.drop_table('idempotency_key')
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_stage_id'))
        batch_op.drop_index(batch_op.f('ix_grade_change_seq'))

    op.drop_table('grade')
    with op.batch_alter_table('bell_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bell_schedule_stage_id'))
        batch_op.drop_index(batch_op.f('ix_bell_schedule_change_seq'))

    op.drop_table('bell_schedule')
    with op.batch_alter_table('weekday', schema=None) as batch_op:
        batch_op.drop_index('uq_weekday_dow_live', postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)
        batch_op.drop_index(batch_op.f('ix_weekday_change_seq'))

    op.drop_table('weekday')
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_change_seq'))

    op.drop_table('subject')
    with op.batch_alter_table('stage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_change_seq'))

    op.drop_table('stage')
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_change_seq'))

    op.drop_table('school')
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_building_change_seq'))

    op.drop_table('building')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_index('uq_app_user_ms_oid_live', postgresql_where=sa.text('ms_oid IS NOT NULL AND deleted_at IS NULL'), postgresql_nulls_not_distinct=False)
        batch_op.drop_index('uq_app_user_email_live', postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)
        batch_op.drop_index(batch_op.f('ix_app_user_change_seq'))

    op.drop_table('app_user')
    op.drop_table('app_setting')
    with op.batch_alter_table('academic_year', schema=None) as batch_op:
        batch_op.drop_index('uq_academic_year_one_current', postgresql_where=sa.text('is_current AND deleted_at IS NULL'), postgresql_nulls_not_distinct=False)
        batch_op.drop_index('uq_academic_year_name_live', postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)
        batch_op.drop_index(batch_op.f('ix_academic_year_change_seq'))

    op.drop_table('academic_year')
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE IF EXISTS global_change_seq")
