"""exam timetable and duty roster

Revision ID: 746f991134fa
Revises: fd0f604996fe
Create Date: 2026-10-02 00:14:32.192461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '746f991134fa'
down_revision = 'fd0f604996fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duty_assignment',
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('weekday_id', sa.UUID(), nullable=True),
    sa.Column('duty_type', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('time_label', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.Time(), nullable=True),
    sa.Column('ends_at', sa.Time(), nullable=True),
    sa.Column('teacher_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_duty_assignment_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], name=op.f('fk_duty_assignment_stage_id_stage')),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], name=op.f('fk_duty_assignment_term_id_term')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_duty_assignment_updated_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['weekday_id'], ['weekday.id'], name=op.f('fk_duty_assignment_weekday_id_weekday')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duty_assignment'))
    )
    with op.batch_alter_table('duty_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duty_assignment_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_duty_assignment_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index('ix_duty_assignment_term_day', ['term_id', 'weekday_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duty_assignment_term_id'), ['term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duty_assignment_weekday_id'), ['weekday_id'], unique=False)

    op.create_table('exam_session',
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=True),
    sa.Column('ends_at', sa.Time(), nullable=True),
    sa.Column('session_label', sa.Text(), nullable=True),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('grade_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('rooms', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_exam_session_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], name=op.f('fk_exam_session_stage_id_stage')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_exam_session_subject_id_subject')),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], name=op.f('fk_exam_session_term_id_term')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_exam_session_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_session'))
    )
    with op.batch_alter_table('exam_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_session_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_session_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_session_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index('ix_exam_session_term_date', ['term_id', 'exam_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_session_term_id'), ['term_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_session_term_id'))
        batch_op.drop_index('ix_exam_session_term_date')
        batch_op.drop_index(batch_op.f('ix_exam_session_subject_id'))
        batch_op.drop_index(batch_op.f('ix_exam_session_stage_id'))
        batch_op.drop_index(batch_op.f('ix_exam_session_change_seq'))

    op.drop_table('exam_session')
    with op.batch_alter_table('duty_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duty_assignment_weekday_id'))
        batch_op.drop_index(batch_op.f('ix_duty_assignment_term_id'))
        batch_op.drop_index('ix_duty_assignment_term_day')
        batch_op.drop_index(batch_op.f('ix_duty_assignment_stage_id'))
        batch_op.drop_index(batch_op.f('ix_duty_assignment_change_seq'))

    op.drop_table('duty_assignment')
    # ### end Alembic commands ###
