"""curriculum plan

Revision ID: c1b98fac5779
Revises: 31265e3d2864
Create Date: 2026-10-02 19:26:31.069453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b98fac5779'
down_revision = '31265e3d2864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_item',
    sa.Column('grade_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('periods_per_week', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), server_default='1', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('duration BETWEEN 1 AND 4', name=op.f('ck_curriculum_item_curriculum_duration_range')),
    sa.CheckConstraint('periods_per_week BETWEEN 1 AND 40', name=op.f('ck_curriculum_item_curriculum_ppw_range')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_curriculum_item_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], name=op.f('fk_curriculum_item_grade_id_grade')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_curriculum_item_subject_id_subject')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_curriculum_item_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculum_item'))
    )
    with op.batch_alter_table('curriculum_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_item_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_item_grade_id'), ['grade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_item_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index('uq_curriculum_live', ['grade_id', 'subject_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curriculum_item', schema=None) as batch_op:
        batch_op.drop_index('uq_curriculum_live', postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)
        batch_op.drop_index(batch_op.f('ix_curriculum_item_subject_id'))
        batch_op.drop_index(batch_op.f('ix_curriculum_item_grade_id'))
        batch_op.drop_index(batch_op.f('ix_curriculum_item_change_seq'))

    op.drop_table('curriculum_item')
    # ### end Alembic commands ###
