"""teacher absences and substitutions

Revision ID: c42459b5a692
Revises: 746f991134fa
Create Date: 2026-10-02 08:54:31.993837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c42459b5a692'
down_revision = '746f991134fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_absence',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('period_from', sa.Integer(), nullable=True),
    sa.Column('period_to', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('(period_from IS NULL) = (period_to IS NULL)', name=op.f('ck_teacher_absence_absence_periods_pair')),
    sa.CheckConstraint('date_to >= date_from', name=op.f('ck_teacher_absence_absence_dates')),
    sa.CheckConstraint('period_from IS NULL OR (period_from >= 1 AND period_to >= period_from)', name=op.f('ck_teacher_absence_absence_periods')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_teacher_absence_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_teacher_absence_teacher_id_teacher')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_teacher_absence_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_absence'))
    )
    with op.batch_alter_table('teacher_absence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_absence_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index('ix_teacher_absence_dates', ['date_from', 'date_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_absence_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('substitution',
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('period_no', sa.Integer(), nullable=False),
    sa.Column('original_teacher_id', sa.UUID(), nullable=False),
    sa.Column('substitute_teacher_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('cover', 'merge', 'cancel', 'none', name='cover_kind', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('change_seq', sa.BigInteger(), server_default=sa.text("nextval('global_change_seq')"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("kind <> 'cover' OR substitute_teacher_id IS NOT NULL", name=op.f('ck_substitution_cover_needs_teacher')),
    sa.CheckConstraint('period_no >= 1', name=op.f('ck_substitution_substitution_period_pos')),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], name=op.f('fk_substitution_card_id_card')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_substitution_created_by_app_user'), use_alter=True),
    sa.ForeignKeyConstraint(['original_teacher_id'], ['teacher.id'], name=op.f('fk_substitution_original_teacher_id_teacher')),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_substitution_room_id_room')),
    sa.ForeignKeyConstraint(['substitute_teacher_id'], ['teacher.id'], name=op.f('fk_substitution_substitute_teacher_id_teacher')),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], name=op.f('fk_substitution_timetable_id_timetable')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_substitution_updated_by_app_user'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_substitution'))
    )
    with op.batch_alter_table('substitution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_substitution_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_substitution_change_seq'), ['change_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_substitution_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_substitution_original_teacher_id'), ['original_teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_substitution_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_substitution_substitute_teacher_id'), ['substitute_teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_substitution_timetable_id'), ['timetable_id'], unique=False)
        batch_op.create_index('uq_substitution_slot_live', ['date', 'card_id', 'period_no', 'original_teacher_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('duty_assignment', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_duty_assignment_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_duty_assignment_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)

    with op.batch_alter_table('exam_session', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_exam_session_created_by_app_user'), 'app_user', ['created_by'], ['id'], use_alter=True)
        batch_op.create_foreign_key(batch_op.f('fk_exam_session_updated_by_app_user'), 'app_user', ['updated_by'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_session', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_exam_session_updated_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_exam_session_created_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('duty_assignment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_duty_assignment_updated_by_app_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_duty_assignment_created_by_app_user'), type_='foreignkey')

    with op.batch_alter_table('substitution', schema=None) as batch_op:
        batch_op.drop_index('uq_substitution_slot_live', postgresql_where=sa.text('deleted_at IS NULL'), postgresql_nulls_not_distinct=False)
        batch_op.drop_index(batch_op.f('ix_substitution_timetable_id'))
        batch_op.drop_index(batch_op.f('ix_substitution_substitute_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_substitution_room_id'))
        batch_op.drop_index(batch_op.f('ix_substitution_original_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_substitution_date'))
        batch_op.drop_index(batch_op.f('ix_substitution_change_seq'))
        batch_op.drop_index(batch_op.f('ix_substitution_card_id'))

    op.drop_table('substitution')
    with op.batch_alter_table('teacher_absence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_absence_teacher_id'))
        batch_op.drop_index('ix_teacher_absence_dates')
        batch_op.drop_index(batch_op.f('ix_teacher_absence_change_seq'))

    op.drop_table('teacher_absence')
    # ### end Alembic commands ###
