"""teacher phone/title, section class teacher

Revision ID: fd0f604996fe
Revises: 5bfbb183f43e
Create Date: 2026-09-27 22:08:02.826595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0f604996fe'
down_revision = '5bfbb183f43e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_teacher_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_section_class_teacher_id'), ['class_teacher_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_section_class_teacher_id_teacher'), 'teacher', ['class_teacher_id'], ['id'])

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('title')
        batch_op.drop_column('phone')

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_section_class_teacher_id_teacher'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_section_class_teacher_id'))
        batch_op.drop_column('class_teacher_id')

    # ### end Alembic commands ###
